### ISSUE TITLE
Foreign key points to a non-existent table

### ISSUE THREAD

**Issue by ewallah** [learnweb/moodle-mod_ratingallocate#108]
Foreign key choiceid on table ratingallocate_allocations points to a non-existent table choices.

**Comment by tobiasreischmann** [comment]
Thanks, for reporting this issue. I totally agree. Till now this bug did not occur to us, since moodle on default does not create any foreign keys. Do you have a platform, which has problems with this issue? Otherwise, due to complexity issues I would like refrain from extending the upgrade file and simply fix the xml file.
