### ISSUE TITLE
Add "Edit choices" page to the settings menu of an instance

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-mod_ratingallocate#119]
Other activity modules (e.g. mod_feedback, mod_questionnaire) add their special configuration pages to the settings menu of their respective instance. This module should add the "Edit choices" page to that menu as well, so that it can be reached from every page of an instance.

**Comment by abias** [comment]
In theme_boost from Moodle 3.2 on, there is no settings menu anymore, only the gear icon menu within the activity. You can add pages to this menu similarly to the way you added pages to the settings menu before. 

However, IMHO this feature is not really benefical as I still think that this activity should be used step by step (i.e. create the choices, then do everything else). That's why I think the starting point for the teacher is the activity's main page, he should get everywhere from there and he can get to this page from everywhere using the breadcrumb.
