### ISSUE TITLE
Broaden Export Possibilities

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#15]
Currently it is possible to export votes and allocation in csv-format, as well as equations in mps-format.
It should be considered to broaden these two possibilities with excel, pdf, .... 

Also it should be discussed whether there should be some extra information in the exports such as the ratebale choices, activity name and so on. Considering than some persons might want to print their exports, they should somehow be able to look at the piece of paper a couple weeks later and still now where it came from.
Problem might be, that exported files with extra information cn't be directly imported again - obviously because they don't fit the format anymore. But for files which can't be imported anyways this doesn't matter, e.g. pdf.

**Comment by tobiasreischmann** [comment]
Additional export possibilities might be nice. However, the csv export should already provide a good tool to automize most of the work. Additional information can be added manually with only low effort. The csv file can then be imported to excel and from there printed as an pdf. Since it is not directly necessary priority is set to very low.

**Comment by Kathrin84** [comment]
After having again a closer look at the CSV export, the following requests are already covered, either in the CSV file itself or in the title:
{quote}
Also it should be discussed whether there should be some extra information in the exports such as the ratebale choices, activity name and so on. Considering than some persons might want to print their exports, they should somehow be able to look at the piece of paper a couple weeks later and still now where it came from.
Problem might be, that exported files with extra information can't be directly imported again - obviously because they don't fit the format anymore. But for files which can't be imported anyways this doesn't matter, e.g. pdf.
{quote}

As the CSV can be imported to Excel, this export functionality is not explicitly needed and as the tables can get quite large in the width a PDF file cannot display this in a good way, so this export possibility can also be shelved.

Therefore, this ticket can be closed @tobiasreischmann. 

Cheers,
Kathrin
