### ISSUE TITLE
Importing choices (from file or groups)

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#16]
Currently there is no other way to define choices other than creating them by hand. 
However, users wish for an alternative (understandable if there are douzens of choices and not only 3 or 4). There are two possible ideas for importing choices:
1. Import choices from a file e.g. a csv
2. Import choices by selecting existing groups from the course (this requires an extra page)

Second option has two advantages:
No extra file import has to be programmed.
A bulk creation for choices is then automatically implemented, as you can already bulk create groups. tada.

It would be the best to have both, but I personally think priority should be the second option (group import)

**Comment by tobiasreischmann** [comment]
First the plugin ratingallocate does no longer focus on group allocation only. Thus a solution should be provided, which simplyfies the creation for all possible scenarios.
Next, in the current implementation the ratingallocate creates its own groups independent of those already existing (even if they have the same name!!!). Thus to be able to join the manually created groups with the ones from the plugin, an group import is mandatory.

Another possible scenario we thought about is a huge text field, where the infromation of the choices can be inputted using a specific syntax.

The development of an import from groups, has a lot of side effect (See all other issues relating to this one). Thus, and because of the number of other scenarios a textual input field should be the first step to take.

**Comment by SonjaKoenig** [comment]
Concerning the textual input field:
Wouldn't it then be possible to import a text file, which is written using that specific syntax? Because the basic idea behind the import is to make ratingallocates easily reproducable (e.g. every semester a course needs seminars).
So what I'm thinking and hoping is, if we have the logic to create choices from syntaxed textinput, the import of text files is a piece of cake.

**Comment by tobiasreischmann** [comment]
Why not using the backup and restore functions for this purpose?

**Comment by SonjaKoenig** [comment]
First time I hear about these functions :D 
Are they provdied by moodle, or are they plugin-related and already implemented? If this works, it sounds like a good alternative.

**Comment by tobiasreischmann** [comment]
Moodle is providing the framework and each plugin has to implement, how it handles these methods. Our plugin is already doing this. This provides the possibilities to backup a whole course containing our plugin and a single plugin instance. This also enables for duplicating plugin instances.

**Comment by SonjaKoenig** [comment]
I guess a backup of a single plugin instance is the way to go.

This should be a page from the activity administration.. Could we somehow promote this option? Because it's not easy to find there. I think a link to the save page on view.php and a link to the restore page on mod_form.php would help.
This lowers the effort immensely.

**Comment by tobiasreischmann** [comment]
Waiting for #76

**Comment by Mulpe** [comment]
An import option would be great indeed.
It would already help to have a simple text field where one could add choices line by line without having to create a choice in a seperate window. I get that it's propably not that far of from an import option but it might be easier to implement.

**Comment by Laur0r** [comment]
CSV import of choices was implemented with #246
