### ISSUE TITLE
Make Manual Allocations Fixed

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#21]
Whenever users are manually assigned to a choice they should stay there even if the algorithm is (re-)run.
For reasons the admin might want to deliberately undo his manual allocation, so he should be given the option to drop his manual allocation, when the algorithm is invoked. Maybe this can be done via an confirmation dialoge -> "yes, but keep manual allocations" or "yes, but drop manual allocations" or "cancel"

Note: If groups can be imported as choices, users may already be in them and should not be kicked out by the algorithm. (see other issue)

**Comment by tobiasreischmann** [comment]
See issue #16: In the current implementation the ratingallocate creates its own groups independent of those already existing (even if they have the same name!!!).  
In which case should it be necessary to rerun the algorithm? The algorithm can only be run, if the rating period is closed. Thus there can be no additional ratings. To be able to keep the manual allocations, either the algorithm has to know, which students are already assigned (and therefore fixed!). This means huge changes to the algorithm. 
Otherwise a student may be assigned two times (one time by the algorithm and one time manually). 

I think this only causes trouble. #22 is a better solution.
