### ISSUE TITLE
Exception : syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'

### ISSUE THREAD

**Issue by gjalam** [learnweb/moodle-mod_ratingallocate#257]
Hello, I am using Moodle 3.11.14+. I updated your plugin to version v4.2-r1 (2023050900), but the update did not go well. Now I'm getting this error when trying to access one of the ratingallocate activities in my Moodle:
**Exception - syntax error, unexpected '=&gt;' (T_DOUBLE_ARROW), expecting ')'

[More information about this error](http://docs.moodle.org/311/en/error/moodle/generalexceptionmessage)

Debug info:
Error code: generalexceptionmessage×Dismiss this notification
Stack trace:
line 672 of /mod/ratingallocate/locallib.php: ParseError thrown**

**Comment by PhMemmel** [comment]
I do not think that reverting back is a good idea, because there have been database changes in this recent update. The best and easiest fix would be to just upgrade to PHP 8.0 (or at least 7.4). If - for whatever reasons - that's not possible for you right now, you can try to use the code of the branch I linked as pull request. Please note that I did not test this at all and using it is at your own risk. I really recommend to update your PHP version.

**Comment by gjalam** [comment]
I sincerely want to thank you for your help and for identifying the issue and providing a solution. Unfortunately, I don't have direct access to the server and won't be able to update the PHP server, which is currently running version 7.3. However, I plan to request my colleagues in the system administration team to consider upgrading to PHP version 8.1 next Monday.
I hope that the development team will consider your proposal to rewrite the code in locallib.php file in a form that is compatible with PHP version 7.3, which Moodle developers still consider compatible with Moodle 3.11 branch.
Thank you again for your help

**Comment by PhMemmel** [comment]
You're welcome. The proper solution would definitely be to update your php version asap, PHP 7.3 does not receive any security updates anymore since end of 2021. However, please note, that Moodle 3.11 is not compatible with PHP 8.1. So if you want to jump to PHP 8.1 you will also have to upgrade Moodle to 4.1. Good luck :-)

**Comment by Laur0r** [comment]
Dear @gjalam,
as @PhMemmel said, we will not support old PHP version which do not receive security updates any more and I would also highly recommend updating PHP to mitigate security risks to your platform!
@PhMemmel thank you very much for providing a patch until then!
