### ISSUE TITLE
E-Mail Notifications

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#26]
There should be a button included to send e-mail notifcations after the distribution has been published.
This can be easily implemented via moodle-messaging. Also, a message type for the plugin should be implemented, so that users can set their preferences about notifcations as usual.

Currently there are some functions in locallib.php which help to prepare e-mails and distribute them. Also there is a task defined in the folder 'classes' for notifying users.
Question is: Does this all actually work and when is the notification performed?

We should include a button in view.php which sends out all these notifications when clicked manually OR make it an option with the activity creation to have notfications sent out automatically on publishing.

**Comment by tobiasreischmann** [comment]
From my knowledge the mails are send at publishing. Or at least at publishing the cron job is informed about the mails to be send. I haven't programmed it myself, so I do not know how it is working exactly.

I do not like the idea of a manual button for this task. If the allocation is published, it should not matter if the student can read it on the site or in his mailbox. The student should be the one to decide, where he gets informed about the published allocations. Otherwise I see the thread in teachers forgetting about sending the email notifications.

I think the possibility for the student to enable or disable automatic notification is still missing.
(Higher priority if messaging is not working at all)

**Comment by kralo** [comment]
The current feature is implemented as an ad-hoc task. locallib.php l.275 queues the tasks and the moodle taskrunner system (which is supposed to be coupled to a cronjob) will then look it up in the aforementioned classes/task/send_distribution_notification.php. The alternative would be to do this in the moodle messaging system but this was done on specific request - not much to configure, not much to go wrong...

**Comment by SonjaKoenig** [comment]
I think we could agree on sending these notifications out automatically at publication.
We should also try to use the existing functions Kralo mentioned, since that might reduce our effort.. 
The enable/disable setting should be added. Is this even possible with Kralo's method?

**Comment by tobiasreischmann** [comment]
This should have been fixed by #156. Closing
