### ISSUE TITLE
SVG Icon broken?

### ISSUE THREAD

**Issue by abias** [learnweb/moodle-mod_ratingallocate#31]
Hi,

if I try to open the /pix/icon.png file in Adobe Illustrator, I get an error message.

Looking at the source code of the SVG file, I see a image tag with a reference to "file:///home/max/Schreibtisch/design-activity-icon-palette.png". This can't be found for sure.

Additionally, the question mark in the SVG file has a white background which covers the grey horizontal lines. This does not look good in my humble opinion.

Could you please ship an improved SVG file?

Thanks,
Alex

**Comment by kralo** [comment]
Hello Alex,

the png is valid, unfortunately I don't have Illustrator. Gimp takes it without complaining.

```
$ pngcheck -v *.png
File: icon.png (1106 bytes)
  chunk IHDR at offset 0x0000c, length 13
    19 x 19 image, 32-bit RGB+alpha, non-interlaced
  chunk sBIT at offset 0x00025, length 4
    red = 8 = 0x08, green = 8 = 0x08, blue = 8 = 0x08, alpha = 8 = 0x08
  chunk pHYs at offset 0x00035, length 9: 2805x2805 pixels/meter (71 dpi)
  chunk tEXt at offset 0x0004a, length 25, keyword: Software
  chunk IDAT at offset 0x0006f, length 975
    zlib: deflated, 2K window, default compression
  chunk IEND at offset 0x0044a, length 0
No errors detected in icon.png (6 chunks, 23.4% compression).
```
Regarding the svg version:
The embedded image had been the moodle color palette (https://docs.moodle.org/dev/File:design-activity-icon-palette.png), but clearly, the reference has nothing to do there. Fixed that in !32. (btw: svg edited with inkscape)
We are free to discuss removal of the background. The intention was to have the question mark stand up from the otherwise transparent background, depending on the moodle style (background-color) and the size the icon is displayed the question mark was not very visible and led to this construction.

**Comment by abias** [comment]
Thanks for removing the broken file reference.

I still can't open the file with Illustrator (btw, opening the Moodle core SVG files is possible with Illustrator), but as you can prove that the file is valid, this shouldn't be your problem ;)

Regarding the white background, I understand your reasons for adding the white background, but I think the implemented solution is suboptimal in terms of design... How about adding a 1-2 px white stroke to the question mark instead of a clumsy square background?

Thanks,
Alex

**Comment by tobiasreischmann** [comment]
Pull request merged.
Still open is the issue with the clumsy white square background.

**Comment by tobiasreischmann** [comment]
Done by #42
