### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Hogol** [learnweb/moodle-mod_ratingallocate#88]
Hi,

Some of our Moodle-Users do have some certain requests for the ratingallocate-plugin. For them, it would be great, if the plugin would (somehow - how to modell the requests would be another topic) have the following features on top:
1. The participants should be able to see, who else has which vote for which choice/group. The scenario would be: students want to be able to join the gruops/votes for which their friends already voted. They want to be able to work togeter in groups with their friends.
2. The participants should be able to choose a different group right after the results are published and the moodle groups are created. That means some new functionality: the user should be able to leave one group for another - als long as in the second group are still some "seats" open. That menas, that groups should then only be chooseable, if the max-students-mark is not reached yet. That again means, that there should be a max-participants functionality for the groups that are managed over the ratingallocate-plugin.
   On top of that, the trainer of the course should be able to manage the gruoups over the ratingallocate-activity. That means: he should be able to push one student from one group to another. And the student learns in which group he actually is, when he has a look into the ratingallocate-activity.
   The functionality is already provided in the "https://moodle.org/plugins/mod_choicegroup" plugin. But we had to get rid of that due to system instabilities caused by this plugin.
   I know that this is a very big thing to implement - but I` just mentioning the desires of (some of) our users :-)
3. The max participants mark should be adjustable even after the results are published. The trainer should be able to expand the number of participants lets say from 10 to 12 if he chooses so.

Anyway: it would be quite perfect for our users, if the trainer (and somehow even the participants) would be able to "edit" the groups/choices even after the results are published and the moodle groups are created.

I know that this is a big issue, and (thanks to you Tobias), I know that one could solve the problem by taking a "https://moodle.org/plugins/mod_choicegroup" right after the moodle groups are created over the ratingallocate plugin. But - as I already mentioned - we had to get rid of the choicegroup pligin. And it would be perfect, if the whole group-choosing-thing and the desired functionality comming along with it, could be handled in one activity: the ratingallocate plugin :-)

We can have some further discussions on this anytime. Cheers and keep up the great work!
Holger

**Comment by tobiasreischmann** [comment]
Dear Holger,

> The participants should be able to see, who else has which vote for which choice/group. The scenario would be: students want to be able to join the gruops/votes for which their friends already voted. They want to be able to work togeter in groups with their friends.
I think it is critical in view of personal data to allow every user to see all other preferences. Nevertheless, a thing I could suggest is, to add an option in the settings menu, which allows all students to view the "ratings and allocations table". However, this does not significantly improve the possibility of ending up in the same group as some friends. Maybe #37 would solve this problem.

> The participants should be able to choose a different group right after the results are published and the moodle groups are created. That means some new functionality: the user should be able to leave one group for another - als long as in the second group are still some "seats" open. That menas, that groups should then only be chooseable, if the max-students-mark is not reached yet. 
This will remove one of the biggest advantages of the plugin. This is, reducing the load peaks, because the choices are not distributed in a first-come-first-serve apporach. Besides such a change in the system does not tackle the reasons for which such a request was made. The vision of the plugin is, to create a optimal allocation of the choices in a way no student should wish to chance the allocation, unless it is not possible due to size restrictions of the choices. If this feature is not fulfilled as expected I would rather try to optimize the algorithms behaviour than just creating a workaround.

> That again means, that there should be a max-participants functionality for the groups that are managed over the ratingallocate-plugin.
Indeed the max-participants can be set in the settings menu of the activity.

> On top of that, the trainer of the course should be able to manage the gruoups over the ratingallocate-activity. That means: he should be able to push one student from one group to another.
The trainer can do this using the manual allocation form.

> And the student learns in which group he actually is, when he has a look into the ratingallocate-activity.
The students should see their allocation in the status informations at the top of the activity's view.

> The max participants mark should be adjustable even after the results are published. The trainer should be able to expand the number of participants lets say from 10 to 12 if he chooses so
For which purpose? I think this is only necessary, if the students would be allowed to change their allocation by themselves, right?

> Anyway: it would be quite perfect for our users, if the trainer (and somehow even the participants) would be able to "edit" the groups/choices even after the results are published and the moodle groups are created.
In theory this is possible. However, the current workflow might not allow it. It is possible this feature is tackled by #78. It would be great if you could share your opinion about a suitable workflow, which is on the one hand clear and strict, and allows on the other hand all scenarios, which are possibily requested by users. Please comment on #78.
