### ISSUE TITLE
Order strategy can prevent that students submit their rating

### ISSUE THREAD

**Issue by tobiasreischmann** [learnweb/moodle-mod_ratingallocate#93]
The mod_form does not prevent to save a ratingallocate instance where students are not able to submit their rating. Following settings are necessary for this case:
- Strategy order
- Number of choices the student has to rate = X
- Number of choices of the instance < X

**Comment by abias** [comment]
As the list of choices isn't created on the activity settings page anymore, the steps to reproduce are different:
* Create a mod_ratingallocate activity:
** Rating strategy: Rating strategy
** Number of fields the user is presented to vote on (smaller than number of choices!): X
* Edit the choices on /mod/ratingallocate/view.php?id=<ACTIVITY-ID>&action=show_choices:
** Add some choices, but keep number of choices < X

Actual result:
* Nothing prevents you from leaving the /mod/ratingallocate/view.php?id=<ACTIVITY-ID>&action=show_choices page and nothing informs you that students won't be able to submit their rating because of your activity settings.

Expected result:
* On /mod/ratingallocate/view.php?id=<ACTIVITY-ID>&action=show_choices, show a warning as long as the number of added choices is < X informing the teacher that students won't be able to submit.
* https://moodle-test.uni-ulm.de/mod/ratingallocate/view.php?id=<ACTIVITY-ID>, show the same warning.
* Optional: To prevent a deadlock for the student, lower X on-the-fly when presenting the rating form to the student so that he can submit his rating even if the teacher did not solve his mistake. In this case, this behaviour should be added to the abovementioned warning message for the teacher so that he is informed what will happen.
